### PR TITLE
H&E manifest

### PR DESCRIPTION
**Pull request by curlup**

### CODE REVIEW

**Comment by curlup** [comment]
@roshni-b can you please elaborate on where do you see descriptions missing? 

I added them to the DM, maybe I'm missing where they are not shown? 
https://github.com/CIMAC-CIDC/cidc-schemas/pull/285/files#diff-b96cc01e4a75f9ad7589e6c31feb9503R324

I might need re-gen docs...

**Comment by roshni-b** [comment]
Don't see the field descriptions appearing as comments in Samples tab of the generated template (template_examples/h_and_e_template.xlsx)

**Comment by curlup** [comment]
Screen Shot 2020-02-04 at 5 41 43 PM
@roshni-b

**Comment by roshni-b** [comment]
Collection event name is fine, I just don't see comments appearing for these particular fields: Tumor Tissue (% total area), Viable Tumor (% area), Viable Stroma (% area), Necrosis (% area), & Fibrosis (% area) in the template with this PR.

(This isn't a real issue, upon re-generating the xlsx they are all showing up alright.)

**Pull request merged**
